[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "multideck-audio-player"
dynamic = ["version"]
description = "Accessible cross-platform audio player for simultaneous playback of multiple audio sources"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
authors = [
    { name = "Steffen Schultz", email = "steffenschultz@mailbox.org" },
]
keywords = [
    "accessibility",
    "audio",
    "mixer",
    "player",
    "screenreader",
    "streaming",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Win32 (MS Windows)",
    "Environment :: MacOS X",
    "Environment :: X11 Applications",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.10",
    "Topic :: Multimedia :: Sound/Audio :: Players",
]
dependencies = [
    "configparser>=6.0.0",
    "numpy>=1.24.0",
    "pedalboard>=0.9.0",
    "prismatoid>=0.15.0",
    "sounddevice>=0.4.6",
    "soundfile>=0.12.1",
    "wxPython>=4.2.0",
    "m45wxcontrols" = { git = "https://github.com/schulle4u/m45wxcontrols", rev = "v0.3.0" }
]

[project.optional-dependencies]
build = [
    "pyinstaller>=6.0.0",
    "markdown>=3.0.0",
]

[project.scripts]
multideck-cli = "main:cli"

[project.gui-scripts]
multideck-gui = "main:main"

[project.urls]
"Bug Reports" = "https://github.com/schulle4u/multideck/issues"
Homepage = "https://m45.dev"
Source = "https://github.com/schulle4u/multideck"

[tool.hatch.build.targets.wheel]
packages = ["src"]
